In [1]:
from keras.models import load_model
import cv2
import numpy as np

Using TensorFlow backend.


In [2]:
model = load_model('model-009.model')

In [7]:
face_clsfr=cv2.CascadeClassifier('Videos/facemask/face-mask-detection-keras-master/haarcascade_frontalface_default.xml')

source=cv2.VideoCapture(0)

labels_dict={0:'MASK',1:'NO MASK'}
color_dict={0:(0,255,0),1:(0,0,255)}

In [8]:
while(True):

    ret,img=source.read()
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=face_clsfr.detectMultiScale(gray,1.3,5)  

    for (x,y,w,h) in faces:
    
        face_img=gray[y:y+w,x:x+w]
        resized=cv2.resize(face_img,(100,100))
        normalized=resized/255.0
        reshaped=np.reshape(normalized,(1,100,100,1))
        result=model.predict(reshaped)
        print(result)
        label=np.argmax(result,axis=1)[0]
        print(label)
      
        cv2.rectangle(img,(x,y),(x+w,y+h),color_dict[label],0)
        cv2.rectangle(img,(x,y-40),(x+w,y),color_dict[label],-1)
        cv2.putText(img, labels_dict[label], (x, y-10),cv2.FONT_HERSHEY_SIMPLEX,0.8,(255,255,255),0)
        
        
    cv2.imshow('LIVE',img)
    key=cv2.waitKey(1)
    
    if(key==27):
        break
        
cv2.destroyAllWindows()
source.release()

[[0.64241827 0.35758168]]
0
[[0.6206065  0.37939346]]
0
[[0.59394443 0.40605554]]
0
[[0.58945876 0.41054124]]
0
[[0.4207004  0.57929957]]
1
[[0.6072901  0.39270994]]
0
[[0.6371512  0.36284876]]
0
[[0.49878505 0.50121486]]
1
[[0.40718007 0.59282   ]]
1
[[0.39878926 0.6012108 ]]
1
[[0.4186247  0.58137536]]
1
[[0.4891953 0.5108047]]
1
[[0.48026988 0.5197301 ]]
1
[[0.21245947 0.78754056]]
1
[[0.12257694 0.87742305]]
1
[[0.21172431 0.7882757 ]]
1
[[0.2706496 0.7293504]]
1
[[0.283578   0.71642196]]
1
[[0.36014447 0.63985544]]
1
[[0.41661465 0.58338535]]
1
[[0.52228254 0.4777175 ]]
0
[[0.53617966 0.46382028]]
0
[[0.5893118  0.41068825]]
0
[[0.55412096 0.44587907]]
0
[[0.7177637  0.28223625]]
0
[[0.65227646 0.34772348]]
0
[[0.72512984 0.27487013]]
0
[[0.62658286 0.37341708]]
0
[[0.59497666 0.4050233 ]]
0
[[0.40926573 0.5907342 ]]
1
[[0.33554915 0.66445076]]
1
[[0.4626431 0.5373569]]
1
[[0.5803132 0.4196867]]
0
[[0.55759794 0.44240203]]
0
[[0.52422154 0.4757785 ]]
0
[[0.52250534 0.4774946 ]]
0


[[0.17496677 0.8250333 ]]
1
[[0.1877021  0.81229794]]
1
[[0.1776365 0.8223635]]
1
[[0.17463063 0.8253694 ]]
1
[[0.17239791 0.827602  ]]
1
[[0.19515689 0.8048432 ]]
1
[[0.2629137 0.7370863]]
1
[[0.43297204 0.5670279 ]]
1
[[0.21765761 0.7823425 ]]
1
[[0.12429334 0.8757066 ]]
1
[[0.12323441 0.8767656 ]]
1
[[0.13585995 0.86414015]]
1
[[0.13774712 0.8622529 ]]
1
[[0.18818116 0.81181884]]
1
[[0.17541501 0.824585  ]]
1
[[0.28916964 0.71083033]]
1
[[0.31338105 0.6866189 ]]
1
[[0.30247867 0.69752127]]
1
[[0.30059168 0.6994083 ]]
1
[[0.20908286 0.7909171 ]]
1
[[0.27433506 0.7256649 ]]
1
[[0.20455608 0.79544395]]
1
[[0.19157168 0.8084283 ]]
1
[[0.14971505 0.850285  ]]
1
[[0.1382213  0.86177874]]
1
[[0.17869735 0.8213026 ]]
1
[[0.24742562 0.7525744 ]]
1
[[0.39973933 0.6002606 ]]
1
[[0.3498962  0.65010375]]
1
[[0.27638432 0.72361565]]
1
[[0.26730257 0.7326974 ]]
1
[[0.16543877 0.8345613 ]]
1
[[0.22846007 0.7715399 ]]
1
[[0.2564092 0.7435908]]
1
[[0.23364423 0.76635575]]
1
[[0.2613394 0.7386605]]
1


[[0.07583205 0.924168  ]]
1
[[0.0793462 0.9206538]]
1
[[0.08137045 0.9186295 ]]
1
[[0.07685447 0.9231456 ]]
1
[[0.07059278 0.9294072 ]]
1
[[0.06497479 0.9350253 ]]
1
[[0.07581146 0.92418855]]
1
[[0.06648323 0.9335168 ]]
1
[[0.07103901 0.92896104]]
1
[[0.07208333 0.9279167 ]]
1
[[0.07121179 0.92878824]]
1
[[0.07127886 0.9287212 ]]
1
[[0.09612511 0.90387493]]
1
[[0.08458158 0.91541845]]
1
[[0.09732698 0.902673  ]]
1
[[0.18214163 0.8178584 ]]
1
[[0.39173573 0.60826427]]
1
[[0.38853765 0.6114623 ]]
1
[[0.6306486  0.36935136]]
0
[[0.287244 0.712756]]
1
[[0.08182079 0.9181792 ]]
1
[[0.12688355 0.8731165 ]]
1
[[0.11964852 0.88035154]]
1
[[0.08510309 0.9148969 ]]
1
[[0.09115888 0.90884113]]
1
[[0.10217077 0.89782923]]
1
[[0.09869705 0.901303  ]]
1
[[0.15132962 0.84867036]]
1
[[0.14890687 0.8510932 ]]
1
[[0.14407748 0.8559225 ]]
1
[[0.6951452  0.30485484]]
0
[[0.19218896 0.8078111 ]]
1
[[0.21948598 0.78051406]]
1
[[0.26170906 0.7382909 ]]
1
[[0.2880657  0.71193427]]
1
[[0.34178066 0.6582193 ]]


[[0.92711073 0.07288933]]
0
[[0.8471615 0.1528385]]
0
[[0.86525613 0.13474388]]
0
[[0.8809912 0.1190088]]
0
[[0.919985   0.08001506]]
0
[[0.9551534  0.04484662]]
0
[[0.9589302  0.04106978]]
0
[[0.9580287 0.0419713]]
0
[[0.96389693 0.03610308]]
0
[[0.93454194 0.0654581 ]]
0
[[0.9642464  0.03575365]]
0
[[0.93863183 0.06136813]]
0
[[0.96911657 0.03088342]]
0
[[0.9766668  0.02333311]]
0
[[0.11306561 0.88693446]]
1
[[0.09096695 0.90903306]]
1
[[0.08286019 0.9171398 ]]
1
[[0.05397277 0.9460273 ]]
1
[[0.06320439 0.9367956 ]]
1
[[0.04920688 0.95079315]]
1
[[0.04113676 0.9588632 ]]
1
[[0.03751266 0.9624874 ]]
1
[[0.05112379 0.94887614]]
1
[[0.04990809 0.95009184]]
1
[[0.05630175 0.9436982 ]]
1
[[0.07516251 0.9248375 ]]
1
[[0.06452785 0.9354722 ]]
1
[[0.07196034 0.92803967]]
1
[[0.07703798 0.92296207]]
1
[[0.07026588 0.9297342 ]]
1
[[0.07043946 0.92956054]]
1
[[0.06888966 0.9311104 ]]
1
[[0.089619   0.91038096]]
1
[[0.06502224 0.93497777]]
1
[[0.0709908 0.9290092]]
1
[[0.07261328 0.92738676]]
1


[[0.06651685 0.9334831 ]]
1
[[0.06583616 0.9341638 ]]
1
[[0.06858246 0.9314175 ]]
1
[[0.05784794 0.942152  ]]
1
[[0.06190732 0.9380927 ]]
1
[[0.06380907 0.93619096]]
1
[[0.06550723 0.93449277]]
1
[[0.0644973 0.9355027]]
1
[[0.06518572 0.9348143 ]]
1
[[0.07137089 0.92862916]]
1
[[0.08770107 0.912299  ]]
1
[[0.06239731 0.93760264]]
1
[[0.06304114 0.9369589 ]]
1
[[0.06510711 0.9348929 ]]
1
[[0.06492244 0.9350776 ]]
1
[[0.05595599 0.94404405]]
1
[[0.06853665 0.93146336]]
1
[[0.07011762 0.92988235]]
1
[[0.06557806 0.9344219 ]]
1
[[0.06506704 0.93493295]]
1
[[0.06599522 0.9340048 ]]
1
[[0.06406882 0.9359312 ]]
1
[[0.06236504 0.93763494]]
1
[[0.0625368  0.93746316]]
1
[[0.06946712 0.93053293]]
1
[[0.07000694 0.9299931 ]]
1
[[0.083808 0.916192]]
1
[[0.07441399 0.925586  ]]
1
[[0.06319562 0.93680435]]
1
[[0.07068039 0.92931956]]
1
[[0.0601298 0.9398702]]
1
[[0.07006865 0.92993134]]
1
[[0.09540409 0.9045959 ]]
1
[[0.07472835 0.92527163]]
1
[[0.06157656 0.9384234 ]]
1
[[0.05327523 0.9467248 ]]
1


[[0.72055703 0.27944297]]
0
[[0.767327   0.23267302]]
0
[[0.8017495  0.19825043]]
0
[[0.80488545 0.19511463]]
0
[[0.8294994  0.17050058]]
0
[[0.82012564 0.17987435]]
0
[[0.66762275 0.33237723]]
0
[[0.7961591  0.20384088]]
0
[[0.89655244 0.1034476 ]]
0
[[0.92175525 0.07824472]]
0
[[0.94408876 0.0559113 ]]
0
[[0.903232   0.09676803]]
0
[[0.89921814 0.10078191]]
0
[[0.92151976 0.0784803 ]]
0
[[0.8875568  0.11244316]]
0
[[0.84890634 0.15109368]]
0
[[0.8889168  0.11108319]]
0
[[0.90078163 0.09921838]]
0
[[0.90637016 0.09362987]]
0
[[0.9215874  0.07841264]]
0
[[0.9472305  0.05276951]]
0
[[0.93017423 0.06982575]]
0
[[0.9482401 0.0517599]]
0
[[0.8687188  0.13128124]]
0
[[0.89279026 0.10720979]]
0
[[0.8855673  0.11443274]]
0
[[0.89933556 0.10066447]]
0
[[0.8925295 0.1074705]]
0
[[0.88528955 0.11471043]]
0
[[0.9052403  0.09475975]]
0
[[0.8444046  0.15559538]]
0
[[0.847966   0.15203395]]
0
[[0.85400444 0.1459955 ]]
0
[[0.8528076  0.14719246]]
0
[[0.85313934 0.14686067]]
0
[[0.8667889  0.13321105]

[[0.9290389  0.07096107]]
0
[[0.87394327 0.12605679]]
0
[[0.62358594 0.37641406]]
0
[[0.7823482  0.21765178]]
0
[[0.8267385  0.17326154]]
0
[[0.90297806 0.097022  ]]
0
[[0.93065774 0.06934226]]
0
[[0.97040606 0.02959394]]
0
[[0.97677237 0.02322769]]
0
[[0.96955955 0.03044046]]
0
[[0.9634505  0.03654953]]
0
[[0.9716204 0.0283796]]
0
[[0.95805347 0.04194648]]
0
[[0.96458626 0.03541379]]
0
[[0.96071327 0.03928675]]
0
[[0.95898545 0.04101459]]
0
[[0.967986   0.03201405]]
0
[[0.96171135 0.0382887 ]]
0
[[0.95976776 0.04023226]]
0
[[0.9759386  0.02406141]]
0
[[0.9655938  0.03440614]]
0
[[0.96758413 0.03241591]]
0
[[0.95234805 0.04765204]]
0
[[0.9563666  0.04363342]]
0
[[0.9728012  0.02719882]]
0
[[0.9747106 0.0252894]]
0
[[0.9630961  0.03690391]]
0
[[0.94819534 0.05180464]]
0
[[0.94240683 0.05759323]]
0
[[0.9512135  0.04878648]]
0
[[0.9737698  0.02623022]]
0
[[0.98254055 0.01745942]]
0
[[0.98307806 0.01692199]]
0
[[0.9833794  0.01662053]]
0
[[0.9891565  0.01084355]]
0
[[0.9680572  0.03194279]

[[0.9821848  0.01781518]]
0
[[0.9846512  0.01534874]]
0
[[0.97978425 0.02021572]]
0
[[0.9795406  0.02045948]]
0
[[0.98597854 0.01402141]]
0
[[0.98161536 0.01838467]]
0
[[0.97353566 0.02646441]]
0
[[0.97973335 0.02026663]]
0
[[0.9685781  0.03142193]]
0
[[0.97918975 0.02081018]]
0
[[0.98306495 0.01693509]]
0
[[0.9774431  0.02255691]]
0
[[0.9834933 0.0165067]]
0
[[0.9780975  0.02190254]]
0
[[0.95174325 0.04825673]]
0
[[0.92278    0.07721999]]
0
[[0.945448   0.05455202]]
0
[[0.9387988  0.06120129]]
0
[[0.9553343  0.04466567]]
0
[[0.9681609 0.0318391]]
0
[[0.962788   0.03721204]]
0
[[0.9782054  0.02179464]]
0
[[0.960191   0.03980897]]
0
[[0.9707609  0.02923912]]
0
[[0.9766004  0.02339955]]
0
[[0.9399665  0.06003342]]
0
[[0.9751931  0.02480691]]
0
[[0.9789082  0.02109179]]
0
[[0.97480136 0.02519869]]
0
[[0.9694876  0.03051232]]
0
[[0.95108545 0.04891457]]
0
[[0.97441286 0.02558711]]
0
[[0.9863464  0.01365353]]
0
[[0.28077692 0.7192231 ]]
1
[[0.26028153 0.7397184 ]]
1
[[0.12289043 0.8771095 ]